DROP TABLE IF EXISTS TBL_HERO;

CREATE TABLE TBL_HERO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

INSERT INTO TBL_HERO (NAME) VALUES
('BATMAN')
,('SPIDERMAN')
,('SUPERMAN')
,('ANTMAN')
,('JOKER')
,('THOR');